Add 03 and 04 (except MeetupsCalendar)
js-tasks-ru/vue-20230905_nikkib pull request #4
Opened 2023-09-21 20:29 UTC by VeronikaMol

2023-09-21 20:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-22 06:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-22 06:17 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-09-22 06:18 UTC, VeronikaMol commented
У меня совсем мало опыта в js, задачу с календарем решить не получилось самостоятельно, пришлось смотреть и разбирать решение преподавателя

2023-09-25 14:22 UTC, ShGKme requested changes
В `04-vue-cli/01-UiFormGroup1` некорректно привязан класс.

В `04-vue-cli/02-TheToaster` требуется добавлять таймер при добавлении тоста, но не через отслеживание изменений массива.

Остальные задачи приняты

2023-09-25 14:22 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +  <div :class="[ form-group, {'form-group_inline': inline }]">
В привязке (как и в почти всех других директивах) значение — это JS выражение (JS Expression).

Так `[ form-group, {'form-group_inline': inline }]` - это JS выражение, описывающее массив. Первый элемент этого массива описан как результат вычисления "значение переменной `form` минус значение переменной `group`".

Чтобы это было имя класса, оно должно быть строкой в кавычках.

2023-09-25 14:22 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +  <div :class="[ form-group, {'form-group_inline': inline }]">
Но во Vue можно разделять описание статичных классов вёрстки и динамически привязанных классов.

```html
<div class="form-group" :class="{ 'form-group_inline': inline }">
```

Так будет отдельно видно обычные статичные классы вёрстки и динамические, зависящие от состояния.

2023-09-25 14:22 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +  },
Отслеживать весь массив `toasts` здесь не совсем корректно. Удалять тост требуется не при любом изменении массива, а при конкретной операции — добавлении массива. Лучше это делать непосредственно при добавлении элемента в методе добавления тоста.

2023-09-25 14:22 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
...это позволит также избавиться от копирования массива, чтобы стриггерить отслеживание

2023-09-25 14:22 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/ToasterItem.vue
Этот компонент не используется

2023-09-25 14:22 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Здесь хорошо подходит метод массива `some`

2023-09-25 14:22 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  }
Обычно с `get*` называют методы, которые что-то вычисляют и возвращают, а не изменяют состояние.
Здесь хорошо подойдёт название `setOption`, `updateSelected`, `select` и т.д.

2023-09-26 05:51 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-09-26 05:54 UTC, VeronikaMol commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  }
Все поправила, спасибо большое

2023-09-26 14:38 UTC, ShGKme approved these changes
Принято, но в дополнительной части есть не совсем корректно работающая функциональность

2023-09-26 14:38 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
Удаление по таймеру через `this.toasts.shift()` не работает вместе с возможностью удалять тост по клику по событию `close`. После удаления тоста таймер для него остаётся и удалит вместо этого следующий тост.

2023-09-26 14:39 UTC, merged